# pylint: disable=line-too-long
from __future__ import annotations

import html
from datetime import date
from pathlib import Path

from . import config, state
from .models import parse_cad_date

_STYLE = """
body{font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;max-width:880px;margin:2rem auto;padding:0 1rem;color:#1a1a2e;background:#fafafe;line-height:1.5}
h1{font-size:1.6rem}h2{margin-top:2rem;border-bottom:1px solid #ddd;padding-bottom:.3rem}
.hero{background:#0b1d3a;color:#fff;padding:1.2rem 1.4rem;border-radius:10px}
.hero .days{font-size:2.4rem;font-weight:700;line-height:1.1}
table{border-collapse:collapse;width:100%;font-size:.92rem}
th,td{text-align:left;padding:.35rem .5rem;border-bottom:1px solid #eee}
.sev-critical{color:#c0392b;font-weight:700}.sev-high{color:#d35400}.sev-info{color:#888}
.muted{color:#888;font-size:.85rem}a{color:#1d4ed8}
"""


def _esc(value: object) -> str:
    return html.escape(str(value))


def _sentry_rows(sentry: dict) -> str:
    objs = [(des, d) for des, d in sentry.items() if d.get("noteworthy")]
    objs.sort(key=lambda kv: kv[1].get("ps_cum", -99.0), reverse=True)
    rows = [
        f"<tr><td>{_esc(des)}</td><td>{_esc(d.get('ts_max', 0))}</td>"
        f"<td>{_esc(d.get('ps_cum'))}</td><td>{d.get('ip', 0.0):.2e}</td></tr>"
        for des, d in objs[:15]
    ]
    return "".join(rows) or "<tr><td colspan='4' class='muted'>none</td></tr>"


def _cad_rows(cad: dict) -> str:
    today = date.today()
    upcoming = []
    for key, d in cad.items():
        des, _, cd = key.partition(":")  # split on the FIRST colon (cd itself contains colons)
        when = parse_cad_date(cd)
        if when is not None and when < today:
            continue  # already happened — this section is "upcoming" only
        upcoming.append((when or date.max, des, cd, d))
    upcoming.sort(key=lambda row: row[0])  # soonest first
    rows = [
        f"<tr><td>{_esc(des)}</td><td>{_esc(cd)}</td>"
        f"<td>{d.get('dist_ld', 0.0):.2f} LD</td>"
        f"<td>{d.get('v_rel_kms', 0.0):.1f} km/s</td>"
        f"<td class='sev-{_esc(d.get('severity', 'info'))}'>{_esc(d.get('severity', 'info'))}</td></tr>"
        for _when, des, cd, d in upcoming[:15]
    ]
    return "".join(rows) or "<tr><td colspan='5' class='muted'>none upcoming</td></tr>"


def _fireball_rows(fireballs: dict) -> str:
    items = sorted(fireballs.items(), key=lambda kv: kv[0], reverse=True)
    rows = [
        f"<tr><td>{_esc(when)}</td><td>{d.get('impact_e_kt', 0.0):.2g} kt</td></tr>"
        for when, d in items[:15]
    ]
    return "".join(rows) or "<tr><td colspan='2' class='muted'>none</td></tr>"


def render(state_dir: Path) -> str:
    sentry = state.load(state_dir / "sentry.json")
    cad = state.load(state_dir / "close_approaches.json")
    fireballs = state.load(state_dir / "fireballs.json")
    meta = state.load(state_dir / "meta.json")
    days = (date.fromisoformat(config.APOPHIS_DATE) - date.today()).days
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Planetary-Defense Watch</title><style>{_STYLE}</style></head>
<body>
<h1>🛰️ Planetary-Defense Watch</h1>
<p class="muted">Material changes in NASA/JPL near-Earth-object data. Last run: {_esc(meta.get('last_run_utc', 'never'))}</p>
<div class="hero"><div>Apophis 2029 close approach</div>
<div class="days">{days} days</div>
<div>until 2029-04-13 — naked-eye visible (~mag 3), and <strong>not</strong> a threat.</div></div>
<h2>Sentry — noteworthy impact-risk objects</h2>
<table><tr><th>Object</th><th>Torino</th><th>Palermo (cum.)</th><th>Impact prob.</th></tr>
{_sentry_rows(sentry)}</table>
<h2>Upcoming close approaches</h2>
<table><tr><th>Object</th><th>Date (UTC)</th><th>Miss distance</th><th>Speed</th><th>Severity</th></tr>
{_cad_rows(cad)}</table>
<h2>Recent fireballs</h2>
<table><tr><th>Date (UTC)</th><th>Impact energy</th></tr>
{_fireball_rows(fireballs)}</table>
<p class="muted">Sources: CNEOS Sentry, CAD &amp; Fireball APIs · generated by <a href="https://github.com/ryroeu/nasa-defense">nasa-defense</a></p>
</body></html>
"""


def write(state_dir: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(render(state_dir), encoding="utf-8")
